# STAGE 1: Build
FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app

COPY 01blog-backend/pom.xml ./
RUN mvn -B -q dependency:go-offline

COPY 01blog-backend/src ./src
RUN mvn -B clean package -DskipTests

# STAGE 2: Run
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# create non-root user
RUN addgroup -S app && adduser -S app -G app
USER app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
